import React, { useMemo, useState } from 'react';
import { LayoutDashboard, Table2, FileText, BarChart3, Settings } from 'lucide-react';
import Designable from './Designable';
import DesignInspector from './DesignInspector';

const pageIcon = { dashboard: LayoutDashboard, list: Table2, detail: FileText, form: FileText, report: BarChart3, settings: Settings };
const sampleRows = (entity) => [1, 2, 3].map(i => Object.fromEntries(Object.keys(entity.schema?.properties || {}).slice(0, 4).map(f => [f, `${f.replace(/_/g, ' ')} ${i}`])));

function PageBody({ page, entities, designMode, selectedId, selectElement, designs }) {
  const linked = entities.find(e => page.description?.toLowerCase().includes(e.name?.toLowerCase())) || entities[0];
  const fields = Object.keys(linked?.schema?.properties || {}).slice(0, 5);
  if (page.type === 'dashboard') return <div className="grid grid-cols-2 gap-3">{entities.slice(0,4).map((e,i)=><Designable key={e.id} id={`metric-${e.id}`} label={`${e.display_name || e.name} card`} enabled={designMode} selectedId={selectedId} onSelect={selectElement} settings={designs[`metric-${e.id}`]} className="ai-preview-card rounded-xl border border-border p-4"><p className="text-xs text-muted-foreground">{e.display_name || e.name}</p><p className="text-2xl font-bold text-foreground mt-1">{(i+1)*12}</p></Designable>)}</div>;
  if (page.type === 'form') return <Designable id="form-panel" label="Form panel" enabled={designMode} selectedId={selectedId} onSelect={selectElement} settings={designs['form-panel']} className="space-y-3 rounded-xl border border-border bg-card p-4">{fields.map(f=><div key={f}><label className="text-xs font-medium capitalize">{f.replace(/_/g,' ')}</label><div className="h-9 rounded-md border border-input bg-background mt-1" /></div>)}<Designable id="primary-button" label="Primary button" enabled={designMode} selectedId={selectedId} onSelect={selectElement} settings={designs['primary-button']} className="inline-block bg-primary text-primary-foreground rounded-md px-4 py-2 text-sm">Save</Designable></Designable>;
  return <Designable id="data-table" label="Data table" enabled={designMode} selectedId={selectedId} onSelect={selectElement} settings={designs['data-table']} className="overflow-hidden rounded-xl border border-border"><table className="w-full text-sm"><thead className="bg-muted/50"><tr>{fields.map(f=><th key={f} className="text-left p-3 capitalize text-xs">{f.replace(/_/g,' ')}</th>)}</tr></thead><tbody>{sampleRows(linked || {}).map((r,i)=><tr key={i} className="border-t border-border">{fields.map(f=><td key={f} className="p-3 text-muted-foreground">{r[f]}</td>)}</tr>)}</tbody></table></Designable>;
}

export default function AppPreviewCanvas({ pages, entities, designMode = false }) {
  const [activeId, setActiveId] = useState(pages[0]?.id);
  const [selected, setSelected] = useState(null);
  const [designs, setDesigns] = useState({});
  const active = useMemo(() => pages.find(p => p.id === activeId) || pages[0], [pages, activeId]);
  const selectElement = (id, label) => setSelected({ id, label });
  const updateSelected = (next) => setDesigns(prev => ({ ...prev, [selected.id]: next }));
  const resetSelected = () => { setDesigns(prev => { const copy = { ...prev }; delete copy[selected.id]; return copy; }); };
  if (!pages.length) return <div className="rounded-xl border border-dashed border-border bg-card/40 p-10 text-center text-sm text-muted-foreground">No UI pages generated yet. Click Generate UI Preview to create screens from your project specs.</div>;
  return <div className="grid grid-cols-1 xl:grid-cols-[1fr_260px] gap-4"><div onClick={() => designMode && setSelected(null)} className="ai-preview-shell rounded-xl border border-border overflow-hidden p-3 min-h-[540px]"><div className="ai-preview-browser rounded-xl border border-border overflow-hidden min-h-[520px]"><div className="h-9 bg-muted/40 border-b border-border flex items-center gap-2 px-3"><span className="w-3 h-3 rounded-full bg-destructive/70"/><span className="w-3 h-3 rounded-full bg-yellow-500/70"/><span className="w-3 h-3 rounded-full bg-accent/70"/><span className="ml-3 text-xs text-muted-foreground">AI generated app preview · {designMode ? 'design mode on' : 'CSS applied'}</span></div><div className="flex min-h-[480px]"><Designable id="sidebar" label="Sidebar" enabled={designMode} selectedId={selected?.id} onSelect={selectElement} settings={designs.sidebar} className="ai-preview-sidebar w-52 text-sidebar-foreground p-4"><h3 className="font-bold text-white text-sm mb-5">{active?.module || 'App'}</h3><nav className="space-y-1">{pages.map(p=>{const Icon=pageIcon[p.type]||LayoutDashboard;return <button key={p.id} onClick={()=>setActiveId(p.id)} className={`w-full flex items-center gap-2 rounded-md px-3 py-2 text-xs text-left transition-all ${active?.id===p.id?'bg-sidebar-active text-white ai-preview-primary-glow':'hover:bg-sidebar-hover'}`}><Icon className="w-3.5 h-3.5" />{p.name}</button>})}</nav></Designable><main className="flex-1 p-6 bg-background"><Designable id="page-header" label="Page header" enabled={designMode} selectedId={selected?.id} onSelect={selectElement} settings={designs['page-header']} className="mb-6"><p className="text-xs text-primary font-medium capitalize">{active?.type || 'page'} · {active?.route}</p><h2 className="text-2xl font-bold text-foreground mt-1">{active?.name}</h2><p className="text-sm text-muted-foreground mt-1">{active?.description}</p></Designable><PageBody page={active || {}} entities={entities} designMode={designMode} selectedId={selected?.id} selectElement={selectElement} designs={designs} /></main></div></div></div>{designMode && <DesignInspector selected={selected} settings={selected ? designs[selected.id] : {}} onChange={updateSelected} onReset={resetSelected} />}</div>;
}