import { createClientFromRequest } from 'npm:@base44/sdk@0.8.31';
import JSZip from 'npm:jszip@3.10.1';

function safeName(name) {
  return String(name || 'app').replace(/[^a-zA-Z0-9_-]/g, '-');
}

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });
    const { projectId } = await req.json();
    const project = await base44.entities.Project.get(projectId);
    const [entities, functions, agents] = await Promise.all([
      base44.entities.EntityDefinition.filter({ project_id: projectId }),
      base44.entities.FunctionDefinition.filter({ project_id: projectId }),
      base44.entities.AgentDefinition.filter({ project_id: projectId })
    ]);
    const zip = new JSZip();
    zip.file('README.md', `# ${project.name}\n\nExported from Sara Builder AI.\n`);
    entities.forEach(e => zip.file(`entities/${safeName(e.name)}.json`, JSON.stringify(e.schema, null, 2)));
    functions.forEach(f => zip.file(`functions/${safeName(f.name)}.js`, f.code || ''));
    agents.forEach(a => zip.file(`agents/${safeName(a.name)}.json`, JSON.stringify({ description: a.description, instructions: a.system_prompt, tool_configs: a.tools || [] }, null, 2)));
    zip.file('pages/Home.jsx', `export default function Home(){return <main className="p-8"><h1>${project.name}</h1><p>Generated by Sara Builder AI.</p></main>}`);
    const base64 = await zip.generateAsync({ type: 'base64' });
    return Response.json({ fileName: `${safeName(project.name)}-base44-export.zip`, base64 });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});