Deno.serve(async (req) => {
  try {
    const { projectName, files, repoName, isPrivate = false } = await req.json();
    const token = Deno.env.get('GITHUB_TOKEN');

    if (!token) return Response.json({ error: 'GITHUB_TOKEN not set' }, { status: 500 });

    const headers = {
      'Authorization': `token ${token}`,
      'Accept': 'application/vnd.github+json',
      'Content-Type': 'application/json',
    };

    // 1. Get authenticated user info
    const userRes = await fetch('https://api.github.com/user', { headers });
    if (!userRes.ok) {
      const errBody = await userRes.text();
      return Response.json({ error: 'Invalid GitHub token: ' + errBody }, { status: 400 });
    }
    const ghUser = await userRes.json();
    const owner = ghUser.login;

    const slug = (repoName || projectName)
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .slice(0, 40);

    // 2. Create repo (ignore 422 if already exists)
    const createRes = await fetch('https://api.github.com/user/repos', {
      method: 'POST',
      headers,
      body: JSON.stringify({
        name: slug,
        description: `Generated by ArchitectAI: ${projectName}`,
        private: isPrivate,
        auto_init: false,
      }),
    });

    let repoUrl;
    if (createRes.ok) {
      const repo = await createRes.json();
      repoUrl = repo.html_url;
    } else {
      repoUrl = `https://github.com/${owner}/${slug}`;
    }

    // Small helper: safely base64-encode UTF-8 content
    function encodeContent(str) {
      const bytes = new TextEncoder().encode(str || '');
      let binary = '';
      for (const b of bytes) binary += String.fromCharCode(b);
      return btoa(binary);
    }

    // 3. Commit each file via the Contents API
    const results = [];
    for (const file of files) {
      const filePath = file.path.startsWith('/') ? file.path.slice(1) : file.path;
      let content;
      try {
        content = encodeContent(file.content || '');
      } catch (e) {
        results.push({ path: filePath, ok: false, error: 'encoding failed' });
        continue;
      }

      // Check if file exists to get sha for update
      let sha;
      try {
        const checkRes = await fetch(
          `https://api.github.com/repos/${owner}/${slug}/contents/${filePath}`,
          { headers }
        );
        if (checkRes.ok) {
          const existing = await checkRes.json();
          sha = existing.sha;
        }
      } catch (_) { /* file doesn't exist yet, no sha needed */ }

      const putRes = await fetch(
        `https://api.github.com/repos/${owner}/${slug}/contents/${filePath}`,
        {
          method: 'PUT',
          headers,
          body: JSON.stringify({
            message: `Add ${filePath}`,
            content,
            ...(sha ? { sha } : {}),
          }),
        }
      );

      const ok = putRes.ok;
      if (!ok) {
        const errText = await putRes.text();
        results.push({ path: filePath, ok: false, error: errText.slice(0, 200) });
      } else {
        results.push({ path: filePath, ok: true });
      }
    }

    const failed = results.filter(r => !r.ok);

    return Response.json({
      repoUrl,
      owner,
      repoName: slug,
      totalFiles: files.length,
      committed: results.filter(r => r.ok).length,
      failed: failed.length,
      failedFiles: failed.map(f => f.path),
    });
  } catch (error) {
    return Response.json({ error: error.message, stack: error.stack?.slice(0, 500) }, { status: 500 });
  }
});