import { createClientFromRequest } from 'npm:@base44/sdk@0.8.31';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

    const { projectName, files, repoName, isPrivate = false } = await req.json();
    const token = Deno.env.get('GITHUB_TOKEN');

    if (!token) return Response.json({ error: 'GITHUB_TOKEN not set' }, { status: 500 });

    const headers = {
      'Authorization': `token ${token}`,
      'Accept': 'application/vnd.github+json',
      'Content-Type': 'application/json',
    };

    // 1. Get authenticated user info
    const userRes = await fetch('https://api.github.com/user', { headers });
    if (!userRes.ok) return Response.json({ error: 'Invalid GitHub token' }, { status: 400 });
    const ghUser = await userRes.json();
    const owner = ghUser.login;

    const slug = repoName || projectName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 40);

    // 2. Create repo (ignore error if already exists)
    const createRes = await fetch('https://api.github.com/user/repos', {
      method: 'POST',
      headers,
      body: JSON.stringify({
        name: slug,
        description: `Generated by ArchitectAI: ${projectName}`,
        private: isPrivate,
        auto_init: false,
      }),
    });

    let repoUrl;
    if (createRes.ok) {
      const repo = await createRes.json();
      repoUrl = repo.html_url;
    } else {
      // Repo may already exist
      repoUrl = `https://github.com/${owner}/${slug}`;
    }

    // 3. Commit each file via the Contents API
    const results = [];
    for (const file of files) {
      const content = btoa(unescape(encodeURIComponent(file.content || '')));
      const filePath = file.path.startsWith('/') ? file.path.slice(1) : file.path;

      // Check if file exists to get sha for update
      let sha;
      const checkRes = await fetch(`https://api.github.com/repos/${owner}/${slug}/contents/${filePath}`, { headers });
      if (checkRes.ok) {
        const existing = await checkRes.json();
        sha = existing.sha;
      }

      const body = {
        message: `Add ${filePath}`,
        content,
        ...(sha ? { sha } : {}),
      };

      const putRes = await fetch(`https://api.github.com/repos/${owner}/${slug}/contents/${filePath}`, {
        method: 'PUT',
        headers,
        body: JSON.stringify(body),
      });

      results.push({ path: filePath, ok: putRes.ok });
    }

    const failed = results.filter(r => !r.ok).length;

    return Response.json({
      repoUrl,
      owner,
      repoName: slug,
      totalFiles: files.length,
      committed: results.filter(r => r.ok).length,
      failed,
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});